import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/navbar.js'
import CarouselHome from '../jumbotronHome/index.js'
import CompanyProfile from '../aboutProfile/companyProfile.js'
import RatingContent from '../rating/index.js'
import Ordering from '../orderingHome.js'
import Footbar from '../components/footbar/footbar'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Luluk Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.navbarArea}>
          <Navbar />
      </div>

      <main className={styles.main}>
        <section className={styles.mainContainer}>
          <CarouselHome />
        </section>
        <section>
          <CompanyProfile />
        </section>
        <section>
          <RatingContent />
        </section>
        <section>
          <Ordering />
        </section>
      </main>

      <footer className={styles.footer}>
        <Footbar />
      </footer>
    </div>
  )
}
