import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/navbar'
import VoucherPoints from '../voucher_points'
import EnhancedSwipeableViews from '../sliderBanner/demo'
import ColorButtons from '../components/categories/categories.js'
import ProductCard from '../product-home/productCard'
import BottomNavigationApp from '../components/footer/footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Freshvo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <section className={styles.mainWrapper}>
          <VoucherPoints />
          <div className={styles.swipeWrapper}>
            <div className={styles.infoBanner}>
              <span className={styles.hInfo}>Informasi Terbaru</span>
              <p className={styles.pInfo}>Informasi Terbaru hanya untukmu</p>
            </div>
            <EnhancedSwipeableViews />
          </div>
        </section>
        <section className={styles.categories}>
          <ColorButtons />
        </section>
        <section className={styles.productHere}>
          <div className={styles.titleHeader}>
            <div className={styles.titleWrapper}>
              <div className={styles.contentTitle}>
                <span className={styles.titleProduct}>Produk Pilihan</span>
                <span className={styles.subtitleProduct}>Produk pilihan yang terbaik untukmu</span>
              </div>
              <span className={styles.others}>Lihat Semua</span>
            </div>
          </div>
          <ProductCard />
        </section>
        <BottomNavigationApp />]
      </main>
    </div>
  )
}
